unstable_features = true
max_width = 120
hard_tabs = true
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true
reorder_modules = true
edition = "2024"
fn_single_line = true
condense_wildcard_suffixes = true
wrap_comments = true
format_code_in_doc_comments = true
